### ISSUE TITLE
问下作者大大，这个支持第三方皮肤站设置的披风吗

### ISSUE THREAD

**Issue by ASHT0120** [hank9999/UseBlessingSkin#1]
如题，我想做一个可以支持加载自定义披风，而不需要另外下皮肤模组

**Comment by hank9999** [comment]
我也想实现，但是因为皮肤数据需要签名，Mojang目前不支持设置披风，MineSkin Api 和 SkinsRestorerX 均不提供支持，没法实现。目前可以设置成有披风的玩家的皮肤 或 使用MOD

https://github.com/SkinsRestorer/SkinsRestorerX/issues/128
https://github.com/SkinsRestorer/SkinSystem/issues/95

**Comment by ASHT0120** [comment]
好的，感谢
