### ISSUE TITLE
保存材质时出现异常

### ISSUE THREAD

**Issue by menxin123** [hank9999/UseBlessingSkin#4]
![Uploading QQ截图20240530211629.png…]()
![Uploading QQ截图20240530211553.png…]()

**Comment by hank9999** [comment]
图好像没传上来

**Comment by menxin123** [comment]
![Uploading QQ截图20240530211553.png…]()
![Uploading QQ截图20240530211629.png…]()

**Comment by menxin123** [comment]
![Uploading QQ截图20240530211553.png…]()
![Uploading QQ截图20240530211629.png…]()

**Comment by menxin123** [comment]
我改了下配置文件，似乎解决问题了，感谢您的回复

**Comment by menxin123** [comment]
我改了下配置文件，似乎解决问题了，感谢您的回复

**Comment by hank9999** [comment]
好的
