### ISSUE TITLE
文件保存成文件夹了

### ISSUE THREAD

**Issue by zip8919** [hank9999/UseBlessingSkin#5]
linux 面板服，保存的皮肤不是文件，而是文件夹
![Screenshot_20240608_212820_com microsoft emmx](https://github.com/hank9999/UseBlessingSkin/assets/110547378/65526b8e-cd21-4d87-a7dd-d4451c6f3b43)

**Comment by hank9999** [comment]
收到 这是因为目录拼接导致 高考完修

**Comment by zip8919** [comment]
还没修好吗

**Comment by hank9999** [comment]
在 v1.3.1 修复
